# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Bitcoin - DevOps"
theme = "syna"
enableGitInfo = true
version = "0.16.1"

# Google Analytics tracking
googleAnalytics = ""

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  name = "Kim Neunert"
  description = "DevOps for Bitcoin related Projects"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    favicon_svg = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#8c1c13"
    secondary = "#4a4063"
    success = "#008f54"
    info = "#c74350"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#c1a5a9"
    dark = "#40434e"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.main]]
  url = "/about"
  name = "About Us"
  weight = 20

[[menu.main]]
  url = "#contact"
  name = "Contact"
  weight = 30


#[[menu.copyright_footer]]
#  url = "/about"
#  name = "About Us"
#  weight = 10

[[menu.copyright_footer]]
  url = "https://unsplash.com/@dennisrochel"
  name = "Photo by Dennis Rochel on Unsplash"
  weight = 30

[[menu.copyright_footer]]
  url = "https://thenounproject.com/rflor/"
  name = "Scrum-Icon by rflor"
  weight = 30

